import {
  Client,
  ShootBooking,
  LedgerEntry,
  Invoice,
  KPISummary,
} from '@/types';

export const mockClients: Client[] = [
  {
    id: 'cli-01',
    name: 'Hélène de Saint-Germain',
    company: 'Maison Margiela Artisanal',
    brandTier: 'HAUTE_COUTURE',
    email: 'h.saintgermain@margiela.paris',
    city: 'Paris',
    totalBilled: 148500,
    totalPaid: 122500,
    status: 'ACTIVE',
  },
  {
    id: 'cli-02',
    name: 'Julian Vance-Kearns',
    company: 'Architectural Digest Global',
    brandTier: 'EDITORIAL_PRESS',
    email: 'jvance@condenast.com',
    city: 'New York',
    totalBilled: 92000,
    totalPaid: 92000,
    status: 'ACTIVE',
  },
  {
    id: 'cli-03',
    name: 'Aurelia Thorne',
    company: 'Boucheron Haute Joaillerie',
    brandTier: 'COMMERCIAL_LUXURY',
    email: 'thorne@boucheron.fr',
    city: 'Geneva',
    totalBilled: 215000,
    totalPaid: 185000,
    status: 'ACTIVE',
  },
  {
    id: 'cli-04',
    name: 'Soren Lindqvist',
    company: 'Acne Studios Stockholm',
    brandTier: 'HAUTE_COUTURE',
    email: 'soren.l@acnestudios.se',
    city: 'Stockholm',
    totalBilled: 74000,
    totalPaid: 58000,
    status: 'ACTIVE',
  },
  {
    id: 'cli-05',
    name: 'Massimo Torricelli',
    company: 'Singer Vehicle Design',
    brandTier: 'COMMERCIAL_LUXURY',
    email: 'massimo@singervehicles.com',
    city: 'Los Angeles',
    totalBilled: 165000,
    totalPaid: 140000,
    status: 'ACTIVE',
  },
];

export const mockShoots: ShootBooking[] = [
  {
    id: 'sht-01',
    shootCode: 'LUM-PARIS-26',
    title: 'Maison Margiela Artisanal Couture Lookbook',
    client: mockClients[0],
    type: 'Haute Couture Editorial',
    status: 'CONFIRMED',
    date: '2026-09-12',
    startTime: '06:30',
    endTime: '19:00',
    callTime: '05:45 AM (Crew Call)',
    location: {
      name: 'Pavillon de l’Arsenal & Quai de Bourbon',
      city: 'Paris IVe, France',
      coordinates: '48.8519° N, 2.3619° E',
      accessCode: 'PORT-C-449',
    },
    productionTeam: [
      { role: 'Creative Director & 1st Camera', name: 'Dan Aurel', initials: 'DA' },
      { role: 'First Assistant Camera (AC)', name: 'Camille Leroux', initials: 'CL' },
      { role: 'Digi Tech & Tethering', name: 'Mathias Wolf', initials: 'MW' },
      { role: 'Key Grip & Briese Tech', name: 'Jean-Luc Vasseur', initials: 'JV' },
      { role: 'Lead Wardrobe Stylist', name: 'Emmanuelle Roche', initials: 'ER' },
    ],
    shotListTotal: 24,
    shotListCompleted: 0,
    financialSummary: {
      totalFee: 48500,
      retainerPaid: 25000,
      balanceDue: 23500,
      currency: 'EUR',
    },
    scheduleTimeline: [
      { time: '05:45', activity: 'Grip & Briese Focus 220 Rigging / Capture One Tether Check', lead: 'Mathias Wolf' },
      { time: '06:30', activity: 'Look 01: Deconstructed Trench at Blue Dawn River Pier', lead: 'Dan Aurel' },
      { time: '09:15', activity: 'Wardrobe Switch & Hair Sculpting (Looks 02-04)', lead: 'Emmanuelle Roche' },
      { time: '12:00', activity: 'Studio Daylight Interior: Raw Linen Silhouettes', lead: 'Dan Aurel' },
      { time: '15:30', activity: 'Monochrome High-Grain Shadow Study (Hasselblad X2D)', lead: 'Dan Aurel' },
      { time: '18:30', activity: 'Wrap & Direct Client Live Export Review', lead: 'Mathias Wolf' },
    ],
    gearAllocated: [
      'Hasselblad H6D-100c + HC 100mm f/2.2',
      'Phase One IQ4 150MP Digital Back',
      'Briese Focus 220 Para Light Generator',
      'Profoto Pro-11 2400W Studio Pack (x2)',
      'Eizo ColorEdge Prominence 4K Field Monitor',
      'Inovativ Scout 37 Digi-Plate Workstation',
    ],
    editorialNotes: 'High-contrast monochrome mixed with desaturated raw sienna tones. Film grain emulation layer to be previewed on live capture.',
  },
  {
    id: 'sht-02',
    shootCode: 'LUM-COMO-88',
    title: 'Architectural Digest: Villa Sospesa Cantilever Feature',
    client: mockClients[1],
    type: 'Architectural Digest Feature',
    status: 'IN_PRODUCTION',
    date: '2026-09-15',
    startTime: '07:00',
    endTime: '21:00',
    callTime: '06:15 AM',
    location: {
      name: 'Villa Sospesa Promontory Estate',
      city: 'Tremezzo, Lake Como, Italy',
      coordinates: '45.9863° N, 9.2274° E',
      accessCode: 'GATE-VILLA-7',
    },
    productionTeam: [
      { role: 'Principal Architectural Eye', name: 'Dan Aurel', initials: 'DA' },
      { role: 'Drone Pilot & Gimbal Tech', name: 'Andrea Bellini', initials: 'AB' },
      { role: 'Staging & Architecture Editor', name: 'Julian Vance-Kearns', initials: 'JV' },
    ],
    shotListTotal: 18,
    shotListCompleted: 6,
    financialSummary: {
      totalFee: 32000,
      retainerPaid: 16000,
      balanceDue: 16000,
      currency: 'EUR',
    },
    scheduleTimeline: [
      { time: '06:15', activity: 'Atmospheric mist capture over glass cantilever infinity pool', lead: 'Dan Aurel' },
      { time: '11:00', activity: 'Interior natural light balance: Ceppo di Gré Stone & walnut joinery', lead: 'Dan Aurel' },
      { time: '17:45', activity: 'Golden Hour exterior architectural elevation with Lake Como reflections', lead: 'Dan Aurel' },
      { time: '20:15', activity: 'Twilight long-exposure illumination capture', lead: 'Andrea Bellini' },
    ],
    gearAllocated: [
      'Cambo WRS-1600 Technical Camera',
      'Rodenstock HR Digaron-W 32mm f/4',
      'Phase One IQ4 150MP Achromatic',
      'Gitzo Systematic Series 5 Carbon Tripod',
      'Arri Orbiter LED High-Output Fresnels',
    ],
    editorialNotes: 'Must maintain flawless parallel verticals. Minimal digital correction required via Cambo shift standards.',
  },
  {
    id: 'sht-03',
    shootCode: 'LUM-VENDOME-14',
    title: 'Boucheron Nocturne High Jewelry Campaign',
    client: mockClients[2],
    type: 'High Jewelry Lookbook',
    status: 'CONFIRMED',
    date: '2026-09-20',
    startTime: '10:00',
    endTime: '22:00',
    callTime: '09:00 AM',
    location: {
      name: 'Salons Historiques 26 Place Vendôme',
      city: 'Paris, France',
      coordinates: '48.8675° N, 2.3294° E',
      accessCode: 'VAULT-SEC-01',
    },
    productionTeam: [
      { role: 'Master Jeweler Still-Life', name: 'Dan Aurel', initials: 'DA' },
      { role: 'Armed Security Detail & Gemologist', name: 'Didier Marais', initials: 'DM' },
      { role: 'Macro Focus-Stacking Specialist', name: 'Chloe Vance', initials: 'CV' },
      { role: 'Precision Lighting Sculptor', name: 'Marc Fontaine', initials: 'MF' },
    ],
    shotListTotal: 30,
    shotListCompleted: 0,
    financialSummary: {
      totalFee: 65000,
      retainerPaid: 35000,
      balanceDue: 30000,
      currency: 'EUR',
    },
    scheduleTimeline: [
      { time: '09:00', activity: 'Jewelry courier handoff and vault inspection', lead: 'Didier Marais' },
      { time: '10:30', activity: 'Setup motorized micro-rail for 80-bracket automated focus stacks', lead: 'Chloe Vance' },
      { time: '14:00', activity: 'Emerald Solitaire & Choker with black acrylic light diffusers', lead: 'Dan Aurel' },
      { time: '19:00', activity: 'Dramatic chiascuro model hand placement with diamond pavé cuffs', lead: 'Dan Aurel' },
    ],
    gearAllocated: [
      'Hasselblad X2D 100C + XCD 120mm Macro',
      'Cognisys StackShot 3X Automated Macro Rail',
      'Broncolor Scoro 3200 S WiFi RFS 2 Power Pack',
      'Picolite Precision Fiber Optic Projector Heads',
    ],
    editorialNotes: 'Zero dust tolerance. Anti-static ion blowers required on set before every single shutter release.',
  },
  {
    id: 'sht-04',
    shootCode: 'LUM-MOJAVE-09',
    title: 'Singer Reimagined: Mojave Salt Flats Monolith Campaign',
    client: mockClients[4],
    type: 'Commercial Campaign',
    status: 'CONFIRMED',
    date: '2026-09-28',
    startTime: '05:00',
    endTime: '20:30',
    callTime: '04:15 AM',
    location: {
      name: 'Trona Pinnacles & Dry Lake Basin',
      city: 'Mojave Desert, CA, USA',
      coordinates: '35.6174° N, 117.3683° W',
      accessCode: 'BLM-PERMIT-4091',
    },
    productionTeam: [
      { role: 'Director of Photography', name: 'Dan Aurel', initials: 'DA' },
      { role: 'Chase Vehicle Driver & Rig', name: 'Chet Brooks', initials: 'CB' },
      { role: 'Digital Imaging Technician (DIT)', name: 'Sven Larson', initials: 'SL' },
    ],
    shotListTotal: 16,
    shotListCompleted: 0,
    financialSummary: {
      totalFee: 58000,
      retainerPaid: 30000,
      balanceDue: 28000,
      currency: 'USD',
    },
    scheduleTimeline: [
      { time: '04:15', activity: 'Rigging low-slung arm on tracking Porsche 964 chase car', lead: 'Chet Brooks' },
      { time: '05:30', activity: 'Dawn high-speed panning sweeps across salt crust', lead: 'Dan Aurel' },
      { time: '13:00', activity: 'Harsh midday brutalist hard light: Carbon fiber weave macro detail', lead: 'Dan Aurel' },
      { time: '18:45', activity: 'Blue dusk silhouette with titanium exhaust glow', lead: 'Dan Aurel' },
    ],
    gearAllocated: [
      'RED V-Raptor XL 8K VV + Cook Full Frame Plus',
      'Hasselblad H6D-100c Aerial Mount',
      'Freefly Systems Tero Off-Road RC Camera Cart',
      'Aputure Electro Storm CS15 LED Monolight',
    ],
    editorialNotes: 'Desert dust sealing critical. Sensor cleanings scheduled after every 2 hours of open-play shooting.',
  },
  {
    id: 'sht-05',
    shootCode: 'LUM-STOCKHOLM-19',
    title: 'Acne Studios: Monolithic Shearling Study',
    client: mockClients[3],
    type: 'Haute Couture Editorial',
    status: 'POST_PROCESSING',
    date: '2026-09-04',
    startTime: '08:00',
    endTime: '18:00',
    callTime: '07:30 AM',
    location: {
      name: 'Artipelag Raw Concrete Atrium',
      city: 'Stockholm Archipelago, Sweden',
      coordinates: '59.3101° N, 18.3444° E',
    },
    productionTeam: [
      { role: 'Lead Photographer', name: 'Dan Aurel', initials: 'DA' },
      { role: 'Producer', name: 'Ebba Bergström', initials: 'EB' },
    ],
    shotListTotal: 22,
    shotListCompleted: 22,
    financialSummary: {
      totalFee: 38000,
      retainerPaid: 38000,
      balanceDue: 0,
      currency: 'EUR',
    },
    scheduleTimeline: [
      { time: '08:00', activity: 'Raw concrete shadow mapping', lead: 'Dan Aurel' },
      { time: '14:00', activity: 'Oversized Shearling in wind corridor', lead: 'Dan Aurel' },
    ],
    gearAllocated: ['Phase One XT IQ4 150MP', 'Broncolor Siros 800 L'],
    editorialNotes: 'Selects locked with client. Final retouching in Master 16-bit ProPhoto RGB underway.',
  },
];

export const mockLedger: LedgerEntry[] = [
  {
    id: 'led-01',
    transactionRef: 'REC-2026-901',
    date: '2026-09-09',
    description: 'Boucheron Place Vendôme — 50% Production Advance',
    category: 'CLIENT_RECEIVABLE',
    type: 'INCOME',
    amount: 35000,
    counterparty: 'Boucheron Haute Joaillerie',
    relatedShootCode: 'LUM-VENDOME-14',
    status: 'CLEARED',
    paymentMethod: 'Wire Transfer / Swift',
  },
  {
    id: 'led-02',
    transactionRef: 'EXP-2026-442',
    date: '2026-09-08',
    description: 'ProFoto Paris — Briese Focus 220 Para & Generator Weekly Rental',
    category: 'GEAR_RENTAL',
    type: 'EXPENSE',
    amount: 4850,
    counterparty: 'ProFoto Paris Equipment Hire',
    relatedShootCode: 'LUM-PARIS-26',
    status: 'CLEARED',
    paymentMethod: 'Corporate Amex Noir',
  },
  {
    id: 'led-03',
    transactionRef: 'REC-2026-898',
    date: '2026-09-06',
    description: 'Maison Margiela Artisanal — Retainer Deposit',
    category: 'CLIENT_RECEIVABLE',
    type: 'INCOME',
    amount: 25000,
    counterparty: 'Maison Margiela',
    relatedShootCode: 'LUM-PARIS-26',
    status: 'CLEARED',
    paymentMethod: 'Wire Transfer / SEPA',
  },
  {
    id: 'led-04',
    transactionRef: 'EXP-2026-440',
    date: '2026-09-05',
    description: 'Digi Tech & Lighting Crew Per-Diem + Production Transport',
    category: 'TALENT_PAYOUT',
    type: 'EXPENSE',
    amount: 3200,
    counterparty: 'Mathias Wolf Digi-Tech Services',
    relatedShootCode: 'LUM-PARIS-26',
    status: 'PENDING',
    paymentMethod: 'Bank Transfer',
  },
  {
    id: 'led-05',
    transactionRef: 'EXP-2026-438',
    date: '2026-09-04',
    description: 'BLM Commercial Film & Location Permit — Trona Basin Basin',
    category: 'LOCATION_PERMIT',
    type: 'EXPENSE',
    amount: 2750,
    counterparty: 'Bureau of Land Management California',
    relatedShootCode: 'LUM-MOJAVE-09',
    status: 'CLEARED',
    paymentMethod: 'US Gov Portal',
  },
  {
    id: 'led-06',
    transactionRef: 'REC-2026-892',
    date: '2026-09-02',
    description: 'Singer Vehicle Design — Mojave Campaign Milestone 1',
    category: 'CLIENT_RECEIVABLE',
    type: 'INCOME',
    amount: 30000,
    counterparty: 'Singer Vehicle Design',
    relatedShootCode: 'LUM-MOJAVE-09',
    status: 'CLEARED',
    paymentMethod: 'Wire Transfer / Fedwire',
  },
  {
    id: 'led-07',
    transactionRef: 'EXP-2026-431',
    date: '2026-08-30',
    description: 'Cambo Technical Shift Lens Calibration & Sensor Alignment',
    category: 'STUDIO_OVERHEAD',
    type: 'EXPENSE',
    amount: 1450,
    counterparty: 'Cambo BV Optical Labs (Netherlands)',
    status: 'CLEARED',
    paymentMethod: 'Direct Debit',
  },
  {
    id: 'led-08',
    transactionRef: 'REC-2026-880',
    date: '2026-08-25',
    description: 'Acne Studios — Final Balance Delivery',
    category: 'CLIENT_RECEIVABLE',
    type: 'INCOME',
    amount: 19000,
    counterparty: 'Acne Studios Stockholm',
    relatedShootCode: 'LUM-STOCKHOLM-19',
    status: 'CLEARED',
    paymentMethod: 'SEPA BACS',
  },
  {
    id: 'led-09',
    transactionRef: 'EXP-2026-429',
    date: '2026-08-24',
    description: 'Lake Como Private Water Taxi & Scouting Boat Charter',
    category: 'PRODUCTION_EXPENSE',
    type: 'EXPENSE',
    amount: 2400,
    counterparty: 'Nautica Como Luxury Charters',
    relatedShootCode: 'LUM-COMO-88',
    status: 'PENDING',
    paymentMethod: 'Corporate Visa',
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: 'inv-101',
    invoiceNumber: 'INV-2026-084',
    clientId: 'cli-01',
    clientName: 'Hélène de Saint-Germain',
    brand: 'Maison Margiela Artisanal',
    issueDate: '2026-09-01',
    dueDate: '2026-09-25',
    items: [
      { id: 'i1', description: 'Principal Photography Day Rate (14h Haute Couture Set)', quantity: 1, unitPrice: 28000, total: 28000 },
      { id: 'i2', description: 'Briese Focus 220 Spec Lighting Package & Generator', quantity: 1, unitPrice: 6500, total: 6500 },
      { id: 'i3', description: 'Digital Capture Station, Digi-Tech, & 3x Live Backup Raid', quantity: 1, unitPrice: 4000, total: 4000 },
      { id: 'i4', description: 'Master Editorial Color Grading & 24 Final Retouched Plates', quantity: 24, unitPrice: 416.66, total: 10000 },
    ],
    subtotal: 48500,
    productionFeeTax: 0,
    totalAmount: 48500,
    balanceDue: 23500,
    status: 'PARTIAL',
  },
  {
    id: 'inv-102',
    invoiceNumber: 'INV-2026-085',
    clientId: 'cli-03',
    clientName: 'Aurelia Thorne',
    brand: 'Boucheron Haute Joaillerie',
    issueDate: '2026-09-03',
    dueDate: '2026-10-03',
    items: [
      { id: 'i5', description: 'Haute Joaillerie Macro Focus Stacking Session', quantity: 1, unitPrice: 38000, total: 38000 },
      { id: 'i6', description: 'Vault Security Protocol & Precision Optical Fiber Rigs', quantity: 1, unitPrice: 12000, total: 12000 },
      { id: 'i7', description: 'High-Bitrate Retouching & Diamond Sparkle Dispersion Grade', quantity: 15, unitPrice: 1000, total: 15000 },
    ],
    subtotal: 65000,
    productionFeeTax: 0,
    totalAmount: 65000,
    balanceDue: 30000,
    status: 'PARTIAL',
  },
  {
    id: 'inv-103',
    invoiceNumber: 'INV-2026-086',
    clientId: 'cli-05',
    clientName: 'Massimo Torricelli',
    brand: 'Singer Vehicle Design',
    issueDate: '2026-08-20',
    dueDate: '2026-09-18',
    items: [
      { id: 'i8', description: 'Mojave Monolith Production Day Rate & Aerial Chase', quantity: 1, unitPrice: 42000, total: 42000 },
      { id: 'i9', description: 'High-G Tracking Camera Cart Rig & Specialized Permits', quantity: 1, unitPrice: 16000, total: 16000 },
    ],
    subtotal: 58000,
    productionFeeTax: 0,
    totalAmount: 58000,
    balanceDue: 28000,
    status: 'PARTIAL',
  },
  {
    id: 'inv-104',
    invoiceNumber: 'INV-2026-081',
    clientId: 'cli-04',
    clientName: 'Soren Lindqvist',
    brand: 'Acne Studios Stockholm',
    issueDate: '2026-08-10',
    dueDate: '2026-08-31',
    items: [
      { id: 'i10', description: 'Stockholm Atrium Editorial Production Day', quantity: 1, unitPrice: 24000, total: 24000 },
      { id: 'i11', description: 'Full Archival Delivery & Global Print Licensing (2 Yrs)', quantity: 1, unitPrice: 14000, total: 14000 },
    ],
    subtotal: 38000,
    productionFeeTax: 0,
    totalAmount: 38000,
    balanceDue: 0,
    status: 'PAID',
  },
];

export const mockKPISummary: KPISummary = {
  netMargins: {
    amount: 142850,
    percentage: 68.4,
    changePct: 12.3,
  },
  cashFlow: {
    current: 184500,
    monthInflow: 109000,
    monthOutflow: 24500,
  },
  confirmedShoots: {
    count: 4,
    activeProductionDays: 7,
  },
  unpaidRetainers: {
    total: 97500,
    count: 3,
  },
};
