import {
  Client,
  ShootBooking,
  LedgerEntry,
  Invoice,
  KPISummary,
  Quotation,
  Enquiry,
} from '@/types';
import { defaultCatalog } from '@/lib/catalogDefaults';

export const mockClients: Client[] = [
  {
    id: 'cli-01',
    name: 'Vanessa D’Souza',
    company: 'The Saffron & Silk Atelier',
    brandTier: 'HAUTE_COUTURE',
    email: 'vanessa@saffronsilk.in',
    city: 'Mangalore',
    totalBilled: 38000,
    totalPaid: 19000,
    status: 'ACTIVE',
  },
  {
    id: 'cli-02',
    name: 'Arvind Hegde',
    company: 'Coastal Habitat & Architectural Digest India',
    brandTier: 'EDITORIAL_PRESS',
    email: 'arvind.hegde@coastalhabitat.in',
    city: 'Udupi',
    totalBilled: 32000,
    totalPaid: 32000,
    status: 'ACTIVE',
  },
  {
    id: 'cli-03',
    name: 'Fathima Zainab Beary',
    company: 'Zohra Fine Heritage Jewels',
    brandTier: 'COMMERCIAL_LUXURY',
    email: 'zainab@zohrajewels.com',
    city: 'Mangalore',
    totalBilled: 42000,
    totalPaid: 21000,
    status: 'ACTIVE',
  },
  {
    id: 'cli-04',
    name: 'Rohan Shetty & Preethi Rai',
    company: 'Sasihithlu Reserve Coastal Botanicals',
    brandTier: 'COMMERCIAL_LUXURY',
    email: 'rohan@sasihithlureserve.com',
    city: 'Mangalore',
    totalBilled: 36000,
    totalPaid: 18000,
    status: 'ACTIVE',
  },
  {
    id: 'cli-05',
    name: 'Noel Alvares',
    company: 'Balur Estate Single-Origin Reserve',
    brandTier: 'PRIVATE_ESTATE',
    email: 'noel@balurestate.com',
    city: 'Chikmagalur / Western Ghats',
    totalBilled: 28000,
    totalPaid: 28000,
    status: 'ACTIVE',
  },
];

export const mockShoots: ShootBooking[] = [
  {
    id: 'sht-01',
    shootCode: 'LUM-MNG-26',
    title: 'Saffron & Silk: Coastal Mangalorean Heirloom Bridal Campaign',
    client: mockClients[0],
    type: 'Haute Couture Editorial',
    status: 'CONFIRMED',
    date: '2026-09-12',
    startTime: '05:45',
    endTime: '19:00',
    callTime: '05:00 AM (Dawn Call)',
    location: {
      name: 'Someshwara Sea Cliff & Heritage Courtyard Bungalow',
      city: 'Ullal, Mangalore',
      coordinates: '12.7984° N, 74.8569° E',
      accessCode: 'COAST-GATE-44',
    },
    productionTeam: [
      { role: 'Studio Director & Lead Camera', name: 'Dan Aurel', initials: 'DA' },
      { role: 'First Camera Assistant', name: 'Roshan D’Silva', initials: 'RD' },
      { role: 'Digital Imaging Technician (DIT)', name: 'Farooq Mansoor', initials: 'FM' },
      { role: 'Lead Wardrobe & Draping Stylist', name: 'Ananya Rai', initials: 'AR' },
      { role: 'Gaffer & Generator Operator', name: 'Santhosh Bhandary', initials: 'SB' },
    ],
    shotListTotal: 25,
    shotListCompleted: 0,
    financialSummary: {
      totalFee: 38000,
      retainerPaid: 19000,
      balanceDue: 19000,
      currency: 'INR',
    },
    scheduleTimeline: [
      { time: '05:00', activity: 'Grip setup at Someshwara rock promontory / Tether check', lead: 'Farooq Mansoor' },
      { time: '05:45', activity: 'Look 01: Crimson raw silk saree against Arabian Sea low-tide spray', lead: 'Dan Aurel' },
      { time: '09:00', activity: 'Look 02: Traditional Kasavu & Antique Gold waistbelt inside courtyard', lead: 'Ananya Rai' },
      { time: '13:00', activity: 'Midday diffused portraits: Handwoven heirloom veil', lead: 'Dan Aurel' },
      { time: '16:45', activity: 'Sunset Look 04: Twilight reflections on wet sand with Profoto B10X fill', lead: 'Dan Aurel' },
      { time: '18:45', activity: 'Wrap, backup verification to dual NVMe drives, client review', lead: 'Farooq Mansoor' },
    ],
    gearAllocated: [
      'Hasselblad H6D-100c + HC 100mm f/2.2',
      'Phase One IQ4 150MP Digital Back',
      'Profoto Pro-11 Studio Generator Pack',
      'Arri SkyPanel S60-C Soft LED Light',
    ],
    editorialNotes: 'Rich coastal monsoon atmospheric tones. Prioritize deep terracotta laterite contrast against emerald and gold silk fabrics.',
    quotationId: 'q-07',
    deliveryStage: 'EDITING_IN_PROGRESS',
    hardDriveReceived: true,
    clientSelectionDone: true,
  },
  {
    id: 'sht-02',
    shootCode: 'LUM-MLP-88',
    title: 'Architectural Digest India: The Padubidri Cantilever Ocean Residence',
    client: mockClients[1],
    type: 'Architectural Digest Feature',
    status: 'IN_PRODUCTION',
    date: '2026-09-15',
    startTime: '06:15',
    endTime: '20:30',
    callTime: '05:30 AM',
    location: {
      name: 'Villa Samudra, Padubidri Coastal Ridge',
      city: 'Udupi District, Coastal Karnataka',
      coordinates: '13.1384° N, 74.7758° E',
      accessCode: 'PADU-VILLA-09',
    },
    productionTeam: [
      { role: 'Principal Architectural Eye', name: 'Dan Aurel', initials: 'DA' },
      { role: 'Technical Camera Assistant', name: 'Roshan D’Silva', initials: 'RD' },
      { role: 'Architecture Editor & Staging', name: 'Arvind Hegde', initials: 'AH' },
    ],
    shotListTotal: 20,
    shotListCompleted: 8,
    financialSummary: {
      totalFee: 32000,
      retainerPaid: 16000,
      balanceDue: 16000,
      currency: 'INR',
    },
    scheduleTimeline: [
      { time: '05:30', activity: 'Pre-dawn blue hour exposure of exposed cast-concrete ocean cantilever', lead: 'Dan Aurel' },
      { time: '10:30', activity: 'Interior natural lighting balance: Teakwood louvers & Ceppo stone', lead: 'Dan Aurel' },
      { time: '16:00', activity: 'Courtyard rainwater harvest pond light-play and reflection angles', lead: 'Arvind Hegde' },
      { time: '18:45', activity: 'Exterior dusk architectural illumination with Arabian Sea horizon', lead: 'Dan Aurel' },
    ],
    gearAllocated: [
      'Cambo WRS-1600 Technical Camera',
      'Rodenstock HR Digaron-W 32mm f/4 Perspective Shift',
      'Gitzo Systematic Series 5 Carbon Tripod',
    ],
    editorialNotes: 'Maintain strict parallel lines. Shift lens calibration required on Cambo standards.',
    deliveryStage: 'SELECTION_PENDING',
    hardDriveReceived: false,
    clientSelectionDone: false,
  },
  {
    id: 'sht-03',
    shootCode: 'LUM-HMP-14',
    title: 'Zohra High Jewelry: Royal Basra Pearls & Colombian Emeralds',
    client: mockClients[2],
    type: 'High Jewelry Lookbook',
    status: 'CONFIRMED',
    date: '2026-09-20',
    startTime: '09:30',
    endTime: '21:00',
    callTime: '08:45 AM',
    location: {
      name: 'Zohra Heritage Vault & Atelier Suite',
      city: 'Hampankatta, Mangalore',
      coordinates: '12.8698° N, 74.8430° E',
      accessCode: 'VAULT-SEC-MNG',
    },
    productionTeam: [
      { role: 'Still-Life Jeweler Eye', name: 'Dan Aurel', initials: 'DA' },
      { role: 'Gemological Curator & Security', name: 'Tariq Beary', initials: 'TB' },
      { role: 'Precision Macro & Focus-Stack Tech', name: 'Farooq Mansoor', initials: 'FM' },
    ],
    shotListTotal: 25,
    shotListCompleted: 0,
    financialSummary: {
      totalFee: 42000,
      retainerPaid: 21000,
      balanceDue: 21000,
      currency: 'INR',
    },
    scheduleTimeline: [
      { time: '08:45', activity: 'Secure courier transfer and vault intake inspection', lead: 'Tariq Beary' },
      { time: '10:00', activity: 'Motorized macro rail calibration for 70-frame focus stacks per piece', lead: 'Farooq Mansoor' },
      { time: '14:00', activity: 'Basra Pearl Choker on custom matte black basalt stone plinth', lead: 'Dan Aurel' },
      { time: '18:30', activity: 'Live model styling with precision fiber-optic snoot lights', lead: 'Dan Aurel' },
    ],
    gearAllocated: [
      'Hasselblad X2D 100C + XCD 120mm f/3.5 Macro',
      'Cognisys StackShot 3X Automated Macro Rail',
      'Broncolor Scoro 3200 S WiFi Studio Pack',
    ],
    editorialNotes: 'Sterile environment protocol. Use anti-static ionizer blowers on all gemstone facets.',
    deliveryStage: 'RAW_INGESTED',
    hardDriveReceived: true,
    clientSelectionDone: false,
  },
  {
    id: 'sht-04',
    shootCode: 'LUM-SSH-09',
    title: 'Sasihithlu Coastal Botanicals: Estuary Dawn Monolith Campaign',
    client: mockClients[3],
    type: 'Commercial Campaign',
    status: 'CONFIRMED',
    date: '2026-09-27',
    startTime: '05:00',
    endTime: '19:30',
    callTime: '04:15 AM',
    location: {
      name: 'Sasihithlu Estuary Sand Spit & River Confluence',
      city: 'Sasihithlu, Mangalore',
      coordinates: '13.0182° N, 74.7865° E',
      accessCode: 'RIVER-PERMIT-2026',
    },
    productionTeam: [
      { role: 'Lead Director of Photography', name: 'Dan Aurel', initials: 'DA' },
      { role: 'Coastal Boatman & River Logistics', name: 'Ganesh Mendon', initials: 'GM' },
      { role: 'Camera Assistant', name: 'Roshan D’Silva', initials: 'RD' },
    ],
    shotListTotal: 18,
    shotListCompleted: 0,
    financialSummary: {
      totalFee: 36000,
      retainerPaid: 18000,
      balanceDue: 18000,
      currency: 'INR',
    },
    scheduleTimeline: [
      { time: '04:15', activity: 'Loading camera cases onto shallow wooden estuary craft', lead: 'Ganesh Mendon' },
      { time: '05:15', activity: 'Sunrise river-mist campaign shot with glass bottle silhouettes', lead: 'Dan Aurel' },
      { time: '11:30', activity: 'Casuarina grove filtered sunlight bottle textures', lead: 'Dan Aurel' },
      { time: '17:45', activity: 'High-contrast tide breaker rocks with sea foam motion blur', lead: 'Dan Aurel' },
    ],
    gearAllocated: [
      'Hasselblad H6D-100c + HC 50mm f/3.5 II',
      'Profoto B10X Plus Location Battery Monolights',
    ],
    editorialNotes: 'High salt mist and tide protection required. Wrap all battery generators in weather housings.',
    deliveryStage: 'RAW_INGESTED',
  },
  {
    id: 'sht-05',
    shootCode: 'LUM-CKM-19',
    title: 'Balur Estate: Western Ghats Coffee Blossom Study',
    client: mockClients[4],
    type: 'Haute Couture Editorial',
    status: 'POST_PROCESSING',
    date: '2026-09-04',
    startTime: '06:00',
    endTime: '17:30',
    callTime: '05:30 AM',
    location: {
      name: 'Balur 1840 Heritage Planter Bungalow',
      city: 'Mudigere, Chikmagalur Foothills',
      coordinates: '13.1362° N, 75.6420° E',
    },
    productionTeam: [
      { role: 'Lead Photographer', name: 'Dan Aurel', initials: 'DA' },
      { role: 'Estate Liaison', name: 'Noel Alvares', initials: 'NA' },
    ],
    shotListTotal: 22,
    shotListCompleted: 22,
    financialSummary: {
      totalFee: 28000,
      retainerPaid: 28000,
      balanceDue: 0,
      currency: 'INR',
    },
    scheduleTimeline: [
      { time: '06:00', activity: 'Western Ghats morning cloud inversion and canopy shadows', lead: 'Dan Aurel' },
      { time: '12:00', activity: 'Deep shade Arabica cherry macro studies', lead: 'Dan Aurel' },
    ],
    gearAllocated: ['Phase One IQ4 150MP Achromatic', 'Profoto B10X Plus'],
    editorialNotes: 'Selects approved by estate trustees. 16-bit Master TIFF files in grading.',
    deliveryStage: 'ALBUM_DESIGN',
    hardDriveReceived: true,
    clientSelectionDone: true,
  },
];

export const mockLedger: LedgerEntry[] = [
  {
    id: 'led-01',
    transactionRef: 'REC-2026-901',
    date: '2026-09-09',
    description: 'Zohra Fine Heritage Jewels — 50% Production Advance',
    category: 'CLIENT_RECEIVABLE',
    type: 'INCOME',
    amount: 21000,
    counterparty: 'Zohra Jewels Hampankatta',
    relatedShootCode: 'LUM-HMP-14',
    status: 'CLEARED',
    paymentMethod: 'RTGS / HDFC Bank Mangalore',
  },
  {
    id: 'led-02',
    transactionRef: 'EXP-2026-442',
    date: '2026-09-08',
    description: 'Kudla Cine Equipment Hire — Profoto Pro-11 Generator Weekly Rental',
    category: 'GEAR_RENTAL',
    type: 'EXPENSE',
    amount: 8500,
    counterparty: 'Kudla Broadcast & Cine Gear Hire',
    relatedShootCode: 'LUM-MNG-26',
    status: 'CLEARED',
    paymentMethod: 'Corporate ICICI Bank Current A/C',
  },
  {
    id: 'led-03',
    transactionRef: 'REC-2026-898',
    date: '2026-09-06',
    description: 'The Saffron & Silk Atelier — Bridal Lookbook Retainer',
    category: 'CLIENT_RECEIVABLE',
    type: 'INCOME',
    amount: 19000,
    counterparty: 'Vanessa D’Souza Couture',
    relatedShootCode: 'LUM-MNG-26',
    status: 'CLEARED',
    paymentMethod: 'NEFT / Axis Bank Mangalore',
  },
  {
    id: 'led-04',
    transactionRef: 'EXP-2026-440',
    date: '2026-09-05',
    description: 'Someshwara Set Crew Batta, Coastal Transit & Generator Fuel',
    category: 'TALENT_PAYOUT',
    type: 'EXPENSE',
    amount: 6200,
    counterparty: 'Roshan D’Silva Crew Logistics',
    relatedShootCode: 'LUM-MNG-26',
    status: 'PENDING',
    paymentMethod: 'UPI Direct',
  },
  {
    id: 'led-05',
    transactionRef: 'EXP-2026-438',
    date: '2026-09-04',
    description: 'Coastal Regulation Zone (CRZ) Beach Filming Regulatory Clearance',
    category: 'LOCATION_PERMIT',
    type: 'EXPENSE',
    amount: 4500,
    counterparty: 'Dakshina Kannada District Administration',
    relatedShootCode: 'LUM-SSH-09',
    status: 'CLEARED',
    paymentMethod: 'Karnataka Seva Sindhu Portal',
  },
  {
    id: 'led-06',
    transactionRef: 'REC-2026-892',
    date: '2026-09-02',
    description: 'Sasihithlu Coastal Botanicals — Milestone Advance 01',
    category: 'CLIENT_RECEIVABLE',
    type: 'INCOME',
    amount: 18000,
    counterparty: 'Sasihithlu Reserve LLP',
    relatedShootCode: 'LUM-SSH-09',
    status: 'CLEARED',
    paymentMethod: 'IMPS Transfer',
  },
  {
    id: 'led-07',
    transactionRef: 'EXP-2026-431',
    date: '2026-08-30',
    description: 'Hasselblad Medium Format Sensor Wet Cleaning & Optical Recalibration',
    category: 'STUDIO_OVERHEAD',
    type: 'EXPENSE',
    amount: 3200,
    counterparty: 'Pro Cine Labs Bangalore',
    status: 'CLEARED',
    paymentMethod: 'Corporate Debit Card',
  },
  {
    id: 'led-08',
    transactionRef: 'REC-2026-880',
    date: '2026-08-25',
    description: 'Balur Estate Chikmagalur — Final Deliverable Settlement',
    category: 'CLIENT_RECEIVABLE',
    type: 'INCOME',
    amount: 14000,
    counterparty: 'Balur Heritage Estate Trust',
    relatedShootCode: 'LUM-CKM-19',
    status: 'CLEARED',
    paymentMethod: 'RTGS / State Bank of India',
  },
  {
    id: 'led-09',
    transactionRef: 'EXP-2026-429',
    date: '2026-08-24',
    description: 'Padubidri Cliff Location Scouting Taxi & Support Boat Hire',
    category: 'PRODUCTION_EXPENSE',
    type: 'EXPENSE',
    amount: 5400,
    counterparty: 'Malpe Coastal Marine Logistics',
    relatedShootCode: 'LUM-MLP-88',
    status: 'PENDING',
    paymentMethod: 'Cash Voucher / Studio Float',
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: 'inv-101',
    invoiceNumber: 'INV-2026-084',
    clientId: 'cli-01',
    clientName: 'Vanessa D’Souza',
    brand: 'The Saffron & Silk Atelier (Mangalore)',
    issueDate: '2026-09-01',
    dueDate: '2026-09-25',
    items: [
      { id: 'i1', description: 'Principal Photography Day Rate (14h Coastal Heritage Set)', quantity: 1, unitPrice: 22000, total: 22000 },
      { id: 'i2', description: 'Profoto Pro-11 Studio Pack & Continuous Lighting Rig', quantity: 1, unitPrice: 6000, total: 6000 },
      { id: 'i3', description: 'Digital Capture Station, DIT Batta & 3x Live NVMe Raid Backup', quantity: 1, unitPrice: 4000, total: 4000 },
      { id: 'i4', description: 'Master Editorial Color Grading & 25 Retouched Plates', quantity: 25, unitPrice: 240, total: 6000 },
    ],
    subtotal: 38000,
    productionFeeTax: 0,
    totalAmount: 38000,
    balanceDue: 19000,
    status: 'PARTIAL',
  },
  {
    id: 'inv-102',
    invoiceNumber: 'INV-2026-085',
    clientId: 'cli-03',
    clientName: 'Fathima Zainab Beary',
    brand: 'Zohra Fine Heritage Jewels',
    issueDate: '2026-09-03',
    dueDate: '2026-10-03',
    items: [
      { id: 'i5', description: 'Heritage Basra & Emerald Macro Focus Stacking Day Rate', quantity: 1, unitPrice: 24000, total: 24000 },
      { id: 'i6', description: 'Precision Optical Snoot Projector & Fiber Optic Rigging', quantity: 1, unitPrice: 8000, total: 8000 },
      { id: 'i7', description: '16-bit Master Retouching & Diamond Dispersion Grading', quantity: 10, unitPrice: 1000, total: 10000 },
    ],
    subtotal: 42000,
    productionFeeTax: 0,
    totalAmount: 42000,
    balanceDue: 21000,
    status: 'PARTIAL',
  },
  {
    id: 'inv-103',
    invoiceNumber: 'INV-2026-086',
    clientId: 'cli-04',
    clientName: 'Rohan Shetty & Preethi Rai',
    brand: 'Sasihithlu Reserve Coastal Botanicals',
    issueDate: '2026-08-20',
    dueDate: '2026-09-18',
    items: [
      { id: 'i8', description: 'Estuary Confluence Dawn Production & Shallow Boat Staging', quantity: 1, unitPrice: 26000, total: 26000 },
      { id: 'i9', description: 'High-Resolution Drone Plate Capture & CRZ Clearances', quantity: 1, unitPrice: 10000, total: 10000 },
    ],
    subtotal: 36000,
    productionFeeTax: 0,
    totalAmount: 36000,
    balanceDue: 18000,
    status: 'PARTIAL',
  },
  {
    id: 'inv-104',
    invoiceNumber: 'INV-2026-081',
    clientId: 'cli-05',
    clientName: 'Noel Alvares',
    brand: 'Balur Estate Single-Origin Reserve',
    issueDate: '2026-08-10',
    dueDate: '2026-08-31',
    items: [
      { id: 'i10', description: 'Western Ghats Arabica Blossom Production Day', quantity: 1, unitPrice: 18000, total: 18000 },
      { id: 'i11', description: 'Full Archival Master Delivery & Brand Usage License (3 Yrs)', quantity: 1, unitPrice: 10000, total: 10000 },
    ],
    subtotal: 28000,
    productionFeeTax: 0,
    totalAmount: 28000,
    balanceDue: 0,
    status: 'PAID',
  },
];

export const mockKPISummary: KPISummary = {
  netMargins: {
    amount: 41800,
    percentage: 69.2,
    changePct: 14.8,
  },
  cashFlow: {
    current: 43500,
    monthInflow: 38000,
    monthOutflow: 12500,
  },
  confirmedShoots: {
    count: 4,
    activeProductionDays: 7,
  },
  unpaidRetainers: {
    total: 39000,
    count: 3,
  },
};

export const mockQuotations: Quotation[] = [
  {
    id: 'q-07',
    quotationNumber: 'Q NO. 07',
    date: '6 August , 2026',
    clientName: 'Alveera D’souza',
    clientCity: 'Mangalore',
    clientPhone: '+91 98450 12849',
    clientEmail: 'alveera.dsouza@gmail.com',
    packageTitle: 'PACKAGE',
    requirements: [
      { id: 'req-01', name: 'Traditional Photography', price: '-', included: true },
      { id: 'req-02', name: 'Candid Photography', price: '-', included: true },
      { id: 'req-03', name: 'Cinematic Highlights', price: '-', included: true },
      { id: 'req-04', name: 'Traditional Videography', price: '-', included: true },
    ],
    deliverables: [
      { id: 'del-01', item: 'Edited High-Resolution Photos', details: '*varies per event generally 500 - 800', included: true },
      { id: 'del-02', item: 'Cinematic Highlight Video', details: '*duration 2-8 mintues', included: true },
      { id: 'del-03', item: 'Full-Length Edited Video', details: '*covers the whole event', included: true },
      { id: 'del-04', item: 'Premium Glossy & MATT Photo Album', details: '*35-40 pages', included: true },
      { id: 'del-05', item: 'Complimentary : Couple photo frame', details: '*archival gallery frame included', included: true },
    ],
    crewAllocation: [
      { id: 'crew-01', role: 'Photographers', number: 2 },
      { id: 'crew-02', role: 'Videographers', number: 2 },
    ],
    termsAndConditions: defaultCatalog.standardTerms,
    totalPrice: 38000, // Strictly below 45000
    advancePercentage: 50,
    status: 'SENT',
    enquiryId: 'enq-101',
    contactPerson: 'DAN AUREL',
    contactPhone: '+91 9380057445',
  },
  {
    id: 'q-08',
    quotationNumber: 'Q NO. 08',
    date: '18 August , 2026',
    clientName: 'Kavya Bhandary & Nithin Rai',
    clientCity: 'Padubidri, Udupi',
    clientPhone: '+91 99001 84720',
    clientEmail: 'nithin.rai@coastaltech.in',
    packageTitle: 'ROYAL COASTAL PACKAGE',
    requirements: [
      { id: 'req-01', name: 'Traditional Photography', price: '-', included: true },
      { id: 'req-02', name: 'Candid Photography', price: '-', included: true },
      { id: 'req-03', name: 'Cinematic Highlights', price: '-', included: true },
      { id: 'req-04', name: 'Traditional Videography', price: '-', included: true },
      { id: 'req-05', name: 'Drone Aerial Cinema Coverage', price: 'Rs 6,000 /-', included: true },
    ],
    deliverables: [
      { id: 'del-01', item: 'Edited High-Resolution Photos', details: '*varies per event generally 600 - 900', included: true },
      { id: 'del-02', item: 'Cinematic Highlight Video', details: '*duration 3-5 mintues with 4K color grade', included: true },
      { id: 'del-03', item: 'Full-Length Edited Video', details: '*covers the whole event in 4K UHD', included: true },
      { id: 'del-04', item: 'Premium Glossy & MATT Photo Album', details: '*35-40 pages', included: true },
      { id: 'del-05', item: 'Complimentary : Couple photo frame', details: '*archival frame included', included: true },
    ],
    crewAllocation: [
      { id: 'crew-01', role: 'Photographers', number: 2 },
      { id: 'crew-02', role: 'Videographers', number: 2 },
      { id: 'crew-03', role: 'Drone Pilots', number: 1 },
    ],
    termsAndConditions: defaultCatalog.standardTerms,
    totalPrice: 42000, // Strictly below 45000
    advancePercentage: 50,
    status: 'ACCEPTED',
    enquiryId: 'enq-102',
    contactPerson: 'DAN AUREL',
    contactPhone: '+91 9380057445',
  },
  {
    id: 'q-09',
    quotationNumber: 'Q NO. 09',
    date: '28 August , 2026',
    clientName: 'Zahid Mansoor Beary',
    clientCity: 'Hampankatta, Mangalore',
    clientPhone: '+91 97412 55901',
    clientEmail: 'zahid.beary@gmail.com',
    packageTitle: 'HERITAGE NIKKAH PACKAGE',
    requirements: [
      { id: 'req-01', name: 'Traditional Photography', price: '-', included: true },
      { id: 'req-02', name: 'Candid Photography', price: '-', included: true },
      { id: 'req-03', name: 'Cinematic Highlights', price: '-', included: true },
      { id: 'req-04', name: 'Traditional Videography', price: '-', included: true },
    ],
    deliverables: [
      { id: 'del-01', item: 'Edited High-Resolution Photos', details: '*varies per event generally 500 - 800', included: true },
      { id: 'del-02', item: 'Cinematic Highlight Video', details: '*duration 2-8 mintues', included: true },
      { id: 'del-03', item: 'Full-Length Edited Video', details: '*covers the whole event', included: true },
      { id: 'del-04', item: 'Premium Glossy & MATT Photo Album', details: '*35-40 pages', included: true },
      { id: 'del-05', item: 'Complimentary : Couple photo frame', details: '*archival gallery frame included', included: true },
    ],
    crewAllocation: [
      { id: 'crew-01', role: 'Photographers', number: 2 },
      { id: 'crew-02', role: 'Videographers', number: 2 },
    ],
    termsAndConditions: defaultCatalog.standardTerms,
    totalPrice: 34000, // Strictly below 45000
    advancePercentage: 50,
    status: 'CONVERTED',
    enquiryId: 'enq-103',
    contactPerson: 'DAN AUREL',
    contactPhone: '+91 9380057445',
  },
];

export const mockEnquiries: Enquiry[] = [
  {
    id: 'enq-101',
    enquiryNumber: 'ENQ-2026-101',
    clientName: 'Alveera D’souza',
    phone: '+91 98450 12849',
    email: 'alveera.dsouza@gmail.com',
    city: 'Mangalore',
    eventDate: '2026-11-20',
    eventType: 'Catholic Nuptials & Ullal Reception',
    estimatedBudget: 38000, // Below 45000
    status: 'QUOTED',
    quotationId: 'q-07',
    notes: 'Bride requested Kasavu church draping coverage and sunset beach portraits.',
    createdAt: '2026-08-05',
  },
  {
    id: 'enq-102',
    enquiryNumber: 'ENQ-2026-102',
    clientName: 'Kavya Bhandary & Nithin Rai',
    phone: '+91 99001 84720',
    email: 'nithin.rai@coastaltech.in',
    city: 'Padubidri, Udupi',
    eventDate: '2026-12-14',
    eventType: 'Traditional Bunt Wedding & Grand Reception',
    estimatedBudget: 42000, // Below 45000
    status: 'QUOTED',
    quotationId: 'q-08',
    notes: 'Requires drone coverage for coastal venue.',
    createdAt: '2026-08-16',
  },
  {
    id: 'enq-103',
    enquiryNumber: 'ENQ-2026-103',
    clientName: 'Zahid Mansoor Beary',
    phone: '+91 97412 55901',
    email: 'zahid.beary@gmail.com',
    city: 'Hampankatta, Mangalore',
    eventDate: '2026-10-18',
    eventType: 'Heritage Nikkah & Banquet',
    estimatedBudget: 34000, // Below 45000
    status: 'CONVERTED',
    quotationId: 'q-09',
    notes: 'Converted to confirmed order. Advance received.',
    createdAt: '2026-08-25',
  },
  {
    id: 'enq-104',
    enquiryNumber: 'ENQ-2026-104',
    clientName: 'Dr. Aaron Pinto & Dr. Sneha Saldanha',
    phone: '+91 98860 33412',
    email: 'aaron.pinto@fathermuller.in',
    city: 'Kadri, Mangalore',
    eventDate: '2026-12-28',
    eventType: 'Church Nuptials & Evening Gala',
    estimatedBudget: 39000, // Below 45000
    status: 'NEW',
    notes: 'Looking for documentary candid photography and 4K cinema coverage.',
    createdAt: '2026-09-08',
  },
];
